'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Sijil_Pendaftaran

    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnPicMofBatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPicMofBatal As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''Button6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button6 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnBatalBumi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBatalBumi As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''Button4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button4 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnBatalPicCidb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBatalPicCidb As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''Button5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button5 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnEditSSM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditSSM As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDeleteSSM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteSSM As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnEditMOF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditMOF As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDeleteMOF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteMOF As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDeleteBidang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteBidang As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnEditPicMof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditPicMof As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDeletePicMof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeletePicMof As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnEditBumi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditBumi As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDeleteBumi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteBumi As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnEditCIDB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditCIDB As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDeleteCIDB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteCIDB As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnEditPicCidb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditPicCidb As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDeletePicCidb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeletePicCidb As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnEditLain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditLain As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDeleteLain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteLain As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDeleteKhusus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteKhusus As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
