'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dashboard

    '''<summary>
    '''txtStatusDraf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatusDraf As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtTungguKelulusan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTungguKelulusan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtDiluluskan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiluluskan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtTerkumpul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTerkumpul As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtTungguPembayaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTungguPembayaran As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtTertunggak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTertunggak As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tblTertunggak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblTertunggak As Global.System.Web.UI.HtmlControls.HtmlTable
End Class
