'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CetakEOT

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblPejabat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPejabat As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblBulTahun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBulTahun As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNostaf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNostaf As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNama As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblJawatan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJawatan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNoMohon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoMohon As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNoTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoTel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''EOTransaksi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EOTransaksi As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''EOTButir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EOTButir As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblJumJam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJumJam2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblJumJam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJumJam1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblJumJam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJumJam As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
