'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Sokong_EOT

    '''<summary>
    '''txtNoMohon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoMohon As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNoStaf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoStaf As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNama As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txttkhMohon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttkhMohon As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGaji control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGaji As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtJwtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJwtn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPjbt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPjbt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtJumJamLulus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJumJamLulus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmaunLulus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmaunLulus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtJumJamTuntut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJumJamTuntut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmaunTuntut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmaunTuntut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPeruntukan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeruntukan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPeruntukanOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeruntukanOT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''totalAmaunNomohon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalAmaunNomohon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txttkhTuntut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttkhTuntut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtJamMulaTuntut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJamMulaTuntut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtJamTamatTuntut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJamTamatTuntut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtJamTuntut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJamTuntut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKadarTuntut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKadarTuntut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmnTuntut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmnTuntut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPegawai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPegawai As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtJamMulaSah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJamMulaSah As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtJamTamatSah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJamTamatSah As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtJamSah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJamSah As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKadarSah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKadarSah As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmnSah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmnSah As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Notify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Notify As Global.SMKB_Web_Portal.Modal_Message
End Class
