'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Pembayaran

    '''<summary>
    '''mvSyarikat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvSyarikat As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''View7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents View7 As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''divStatusBayar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStatusBayar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divStatusIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStatusIcon As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MsgStatusBayar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgStatusBayar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divBayar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBayar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''frame1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frame1 As Global.System.Web.UI.HtmlControls.HtmlIframe

    '''<summary>
    '''lbtnPrevPembayaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnPrevPembayaran As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnNextPembayaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnNextPembayaran As Global.System.Web.UI.WebControls.LinkButton
End Class
