'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Daftar_Pot

    '''<summary>
    '''noMohon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noMohon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlKodTrans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKodTrans As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rqdKod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqdKod As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtMula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMula As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''rqdTkhMula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqdTkhMula As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtTamat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTamat As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''rqdTkhTmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqdTkhTmt As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtamaun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtamaun As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''rqdAmaun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqdAmaun As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnView As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
